"""Ajout medecin_id dans patientss

Revision ID: 75a632821880
Revises: 8abd8276dbf7
Create Date: 2025-09-25 10:14:07.533027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75a632821880'
down_revision = '8abd8276dbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('prenom')
        batch_op.drop_column('nom')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('medecin_id'))
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'patientss', ['patients_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patientss', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('medecin_id'))
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('date_naissance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_naissance', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('medecin_id'), ['admin_id'], unique=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('medecin_id'), ['admin_id'], unique=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('prenom', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
