"""Ajout de reponse_secrete_hash_hash dans Admin

Revision ID: a0e087dec647
Revises: 
Create Date: 2025-09-23 10:14:30.274978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0e087dec647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_documents_patients'))

    op.drop_table('documents')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reponse_secrete_hash_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('date_creation',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('reponse_secrete_hash')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patientss', ['patients_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patientss', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientss', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reponse_secrete_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('date_creation',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('reponse_secrete_hash_hash')

    op.create_table('documents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patients_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('ordonnance', 'analyse', 'imagerie', 'autre'), server_default=sa.text("'autre'"), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_upload', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fk_documents_patients'), ['patients_id'], unique=False)

    # ### end Alembic commands ###
